# Generated by Django 3.1.5 on 2021-04-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=30)),
                ('position', models.DateField(db_column='Position')),
                ('doj', models.DateField(db_column='DOJ')),
                ('dob', models.DateField(db_column='DOB')),
                ('salary', models.IntegerField(db_column='Salary')),
            ],
            options={
                'db_table': 'test_table',
                'managed': False,
            },
        ),
    ]
